[package]
name = "cluster-core"
version = "0.1.0"
edition = "2024"

[features]
std = ["serde/std"]

[dependencies]
embedded-graphics = { workspace = true }
heapless = { workspace = true, features = ["serde"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
